name = "j-rides"
main = "src/index.js"
compatibility_date = "2024-08-01"
account_id = "e990188c49f4ff2cb3c91ff2b210e6ce"

routes = [
  { pattern = "j-rides.vip", custom_domain = true },
  { pattern = "www.j-rides.vip", custom_domain = true },
]

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "CONFIG"
id = "e8fa456cf70c489da934306f39491e72"

[vars]
SITE_URL = "https://j-rides.vip"
BOOKING_PHONE = "+13238189982"
NOTIFY_EMAIL = "jeffreysila@gmail.com"
NOTIFY_FROM_EMAIL = "booking@j-rides.vip"
TIMEZONE = "America/Chicago"
MIN_LEAD_MINUTES = "120"

[[send_email]]
name = "EMAIL"
remote = true
